// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/cybozu-go/scim-server/ent/runtime.go

const (
	Version = "v0.11.0"                                         // Version of ent codegen.
	Sum     = "h1:4G5GKmXOpHnIbWIkY2nZvNmuXmHpKWC4SYV1bqfoyZY=" // Sum of ent codegen.
)
