// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cybozu-go/scim-server/ent/entitlement"
	"github.com/cybozu-go/scim-server/ent/predicate"
	"github.com/cybozu-go/scim-server/ent/user"
	"github.com/google/uuid"
)

// EntitlementUpdate is the builder for updating Entitlement entities.
type EntitlementUpdate struct {
	config
	hooks    []Hook
	mutation *EntitlementMutation
}

// Where appends a list predicates to the EntitlementUpdate builder.
func (eu *EntitlementUpdate) Where(ps ...predicate.Entitlement) *EntitlementUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetDisplay sets the "display" field.
func (eu *EntitlementUpdate) SetDisplay(s string) *EntitlementUpdate {
	eu.mutation.SetDisplay(s)
	return eu
}

// SetNillableDisplay sets the "display" field if the given value is not nil.
func (eu *EntitlementUpdate) SetNillableDisplay(s *string) *EntitlementUpdate {
	if s != nil {
		eu.SetDisplay(*s)
	}
	return eu
}

// ClearDisplay clears the value of the "display" field.
func (eu *EntitlementUpdate) ClearDisplay() *EntitlementUpdate {
	eu.mutation.ClearDisplay()
	return eu
}

// SetPrimary sets the "primary" field.
func (eu *EntitlementUpdate) SetPrimary(b bool) *EntitlementUpdate {
	eu.mutation.SetPrimary(b)
	return eu
}

// SetNillablePrimary sets the "primary" field if the given value is not nil.
func (eu *EntitlementUpdate) SetNillablePrimary(b *bool) *EntitlementUpdate {
	if b != nil {
		eu.SetPrimary(*b)
	}
	return eu
}

// ClearPrimary clears the value of the "primary" field.
func (eu *EntitlementUpdate) ClearPrimary() *EntitlementUpdate {
	eu.mutation.ClearPrimary()
	return eu
}

// SetType sets the "type" field.
func (eu *EntitlementUpdate) SetType(s string) *EntitlementUpdate {
	eu.mutation.SetType(s)
	return eu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (eu *EntitlementUpdate) SetNillableType(s *string) *EntitlementUpdate {
	if s != nil {
		eu.SetType(*s)
	}
	return eu
}

// ClearType clears the value of the "type" field.
func (eu *EntitlementUpdate) ClearType() *EntitlementUpdate {
	eu.mutation.ClearType()
	return eu
}

// SetValue sets the "value" field.
func (eu *EntitlementUpdate) SetValue(s string) *EntitlementUpdate {
	eu.mutation.SetValue(s)
	return eu
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (eu *EntitlementUpdate) SetNillableValue(s *string) *EntitlementUpdate {
	if s != nil {
		eu.SetValue(*s)
	}
	return eu
}

// ClearValue clears the value of the "value" field.
func (eu *EntitlementUpdate) ClearValue() *EntitlementUpdate {
	eu.mutation.ClearValue()
	return eu
}

// SetUserID sets the "user" edge to the User entity by ID.
func (eu *EntitlementUpdate) SetUserID(id uuid.UUID) *EntitlementUpdate {
	eu.mutation.SetUserID(id)
	return eu
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (eu *EntitlementUpdate) SetNillableUserID(id *uuid.UUID) *EntitlementUpdate {
	if id != nil {
		eu = eu.SetUserID(*id)
	}
	return eu
}

// SetUser sets the "user" edge to the User entity.
func (eu *EntitlementUpdate) SetUser(u *User) *EntitlementUpdate {
	return eu.SetUserID(u.ID)
}

// Mutation returns the EntitlementMutation object of the builder.
func (eu *EntitlementUpdate) Mutation() *EntitlementMutation {
	return eu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (eu *EntitlementUpdate) ClearUser() *EntitlementUpdate {
	eu.mutation.ClearUser()
	return eu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *EntitlementUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(eu.hooks) == 0 {
		affected, err = eu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EntitlementMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			eu.mutation = mutation
			affected, err = eu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(eu.hooks) - 1; i >= 0; i-- {
			if eu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = eu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, eu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EntitlementUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EntitlementUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EntitlementUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (eu *EntitlementUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   entitlement.Table,
			Columns: entitlement.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: entitlement.FieldID,
			},
		},
	}
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.Display(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: entitlement.FieldDisplay,
		})
	}
	if eu.mutation.DisplayCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: entitlement.FieldDisplay,
		})
	}
	if value, ok := eu.mutation.Primary(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: entitlement.FieldPrimary,
		})
	}
	if eu.mutation.PrimaryCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Column: entitlement.FieldPrimary,
		})
	}
	if value, ok := eu.mutation.GetType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: entitlement.FieldType,
		})
	}
	if eu.mutation.TypeCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: entitlement.FieldType,
		})
	}
	if value, ok := eu.mutation.Value(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: entitlement.FieldValue,
		})
	}
	if eu.mutation.ValueCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: entitlement.FieldValue,
		})
	}
	if eu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlement.UserTable,
			Columns: []string{entitlement.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlement.UserTable,
			Columns: []string{entitlement.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entitlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// EntitlementUpdateOne is the builder for updating a single Entitlement entity.
type EntitlementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EntitlementMutation
}

// SetDisplay sets the "display" field.
func (euo *EntitlementUpdateOne) SetDisplay(s string) *EntitlementUpdateOne {
	euo.mutation.SetDisplay(s)
	return euo
}

// SetNillableDisplay sets the "display" field if the given value is not nil.
func (euo *EntitlementUpdateOne) SetNillableDisplay(s *string) *EntitlementUpdateOne {
	if s != nil {
		euo.SetDisplay(*s)
	}
	return euo
}

// ClearDisplay clears the value of the "display" field.
func (euo *EntitlementUpdateOne) ClearDisplay() *EntitlementUpdateOne {
	euo.mutation.ClearDisplay()
	return euo
}

// SetPrimary sets the "primary" field.
func (euo *EntitlementUpdateOne) SetPrimary(b bool) *EntitlementUpdateOne {
	euo.mutation.SetPrimary(b)
	return euo
}

// SetNillablePrimary sets the "primary" field if the given value is not nil.
func (euo *EntitlementUpdateOne) SetNillablePrimary(b *bool) *EntitlementUpdateOne {
	if b != nil {
		euo.SetPrimary(*b)
	}
	return euo
}

// ClearPrimary clears the value of the "primary" field.
func (euo *EntitlementUpdateOne) ClearPrimary() *EntitlementUpdateOne {
	euo.mutation.ClearPrimary()
	return euo
}

// SetType sets the "type" field.
func (euo *EntitlementUpdateOne) SetType(s string) *EntitlementUpdateOne {
	euo.mutation.SetType(s)
	return euo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (euo *EntitlementUpdateOne) SetNillableType(s *string) *EntitlementUpdateOne {
	if s != nil {
		euo.SetType(*s)
	}
	return euo
}

// ClearType clears the value of the "type" field.
func (euo *EntitlementUpdateOne) ClearType() *EntitlementUpdateOne {
	euo.mutation.ClearType()
	return euo
}

// SetValue sets the "value" field.
func (euo *EntitlementUpdateOne) SetValue(s string) *EntitlementUpdateOne {
	euo.mutation.SetValue(s)
	return euo
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (euo *EntitlementUpdateOne) SetNillableValue(s *string) *EntitlementUpdateOne {
	if s != nil {
		euo.SetValue(*s)
	}
	return euo
}

// ClearValue clears the value of the "value" field.
func (euo *EntitlementUpdateOne) ClearValue() *EntitlementUpdateOne {
	euo.mutation.ClearValue()
	return euo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (euo *EntitlementUpdateOne) SetUserID(id uuid.UUID) *EntitlementUpdateOne {
	euo.mutation.SetUserID(id)
	return euo
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (euo *EntitlementUpdateOne) SetNillableUserID(id *uuid.UUID) *EntitlementUpdateOne {
	if id != nil {
		euo = euo.SetUserID(*id)
	}
	return euo
}

// SetUser sets the "user" edge to the User entity.
func (euo *EntitlementUpdateOne) SetUser(u *User) *EntitlementUpdateOne {
	return euo.SetUserID(u.ID)
}

// Mutation returns the EntitlementMutation object of the builder.
func (euo *EntitlementUpdateOne) Mutation() *EntitlementMutation {
	return euo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (euo *EntitlementUpdateOne) ClearUser() *EntitlementUpdateOne {
	euo.mutation.ClearUser()
	return euo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *EntitlementUpdateOne) Select(field string, fields ...string) *EntitlementUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Entitlement entity.
func (euo *EntitlementUpdateOne) Save(ctx context.Context) (*Entitlement, error) {
	var (
		err  error
		node *Entitlement
	)
	if len(euo.hooks) == 0 {
		node, err = euo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EntitlementMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			euo.mutation = mutation
			node, err = euo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(euo.hooks) - 1; i >= 0; i-- {
			if euo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = euo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, euo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EntitlementUpdateOne) SaveX(ctx context.Context) *Entitlement {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *EntitlementUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EntitlementUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (euo *EntitlementUpdateOne) sqlSave(ctx context.Context) (_node *Entitlement, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   entitlement.Table,
			Columns: entitlement.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: entitlement.FieldID,
			},
		},
	}
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Entitlement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entitlement.FieldID)
		for _, f := range fields {
			if !entitlement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entitlement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.Display(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: entitlement.FieldDisplay,
		})
	}
	if euo.mutation.DisplayCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: entitlement.FieldDisplay,
		})
	}
	if value, ok := euo.mutation.Primary(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: entitlement.FieldPrimary,
		})
	}
	if euo.mutation.PrimaryCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Column: entitlement.FieldPrimary,
		})
	}
	if value, ok := euo.mutation.GetType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: entitlement.FieldType,
		})
	}
	if euo.mutation.TypeCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: entitlement.FieldType,
		})
	}
	if value, ok := euo.mutation.Value(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: entitlement.FieldValue,
		})
	}
	if euo.mutation.ValueCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: entitlement.FieldValue,
		})
	}
	if euo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlement.UserTable,
			Columns: []string{entitlement.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlement.UserTable,
			Columns: []string{entitlement.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Entitlement{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entitlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
