// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cybozu-go/scim-server/ent/group"
	"github.com/cybozu-go/scim-server/ent/groupmember"
	"github.com/cybozu-go/scim-server/ent/predicate"
	"github.com/cybozu-go/scim-server/ent/user"
	"github.com/google/uuid"
)

// GroupMemberUpdate is the builder for updating GroupMember entities.
type GroupMemberUpdate struct {
	config
	hooks    []Hook
	mutation *GroupMemberMutation
}

// Where appends a list predicates to the GroupMemberUpdate builder.
func (gmu *GroupMemberUpdate) Where(ps ...predicate.GroupMember) *GroupMemberUpdate {
	gmu.mutation.Where(ps...)
	return gmu
}

// SetValue sets the "value" field.
func (gmu *GroupMemberUpdate) SetValue(s string) *GroupMemberUpdate {
	gmu.mutation.SetValue(s)
	return gmu
}

// SetType sets the "type" field.
func (gmu *GroupMemberUpdate) SetType(s string) *GroupMemberUpdate {
	gmu.mutation.SetType(s)
	return gmu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (gmu *GroupMemberUpdate) SetNillableType(s *string) *GroupMemberUpdate {
	if s != nil {
		gmu.SetType(*s)
	}
	return gmu
}

// ClearType clears the value of the "type" field.
func (gmu *GroupMemberUpdate) ClearType() *GroupMemberUpdate {
	gmu.mutation.ClearType()
	return gmu
}

// SetRef sets the "ref" field.
func (gmu *GroupMemberUpdate) SetRef(s string) *GroupMemberUpdate {
	gmu.mutation.SetRef(s)
	return gmu
}

// SetNillableRef sets the "ref" field if the given value is not nil.
func (gmu *GroupMemberUpdate) SetNillableRef(s *string) *GroupMemberUpdate {
	if s != nil {
		gmu.SetRef(*s)
	}
	return gmu
}

// ClearRef clears the value of the "ref" field.
func (gmu *GroupMemberUpdate) ClearRef() *GroupMemberUpdate {
	gmu.mutation.ClearRef()
	return gmu
}

// SetUserID sets the "user" edge to the User entity by ID.
func (gmu *GroupMemberUpdate) SetUserID(id uuid.UUID) *GroupMemberUpdate {
	gmu.mutation.SetUserID(id)
	return gmu
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (gmu *GroupMemberUpdate) SetNillableUserID(id *uuid.UUID) *GroupMemberUpdate {
	if id != nil {
		gmu = gmu.SetUserID(*id)
	}
	return gmu
}

// SetUser sets the "user" edge to the User entity.
func (gmu *GroupMemberUpdate) SetUser(u *User) *GroupMemberUpdate {
	return gmu.SetUserID(u.ID)
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (gmu *GroupMemberUpdate) SetGroupID(id uuid.UUID) *GroupMemberUpdate {
	gmu.mutation.SetGroupID(id)
	return gmu
}

// SetNillableGroupID sets the "group" edge to the Group entity by ID if the given value is not nil.
func (gmu *GroupMemberUpdate) SetNillableGroupID(id *uuid.UUID) *GroupMemberUpdate {
	if id != nil {
		gmu = gmu.SetGroupID(*id)
	}
	return gmu
}

// SetGroup sets the "group" edge to the Group entity.
func (gmu *GroupMemberUpdate) SetGroup(g *Group) *GroupMemberUpdate {
	return gmu.SetGroupID(g.ID)
}

// Mutation returns the GroupMemberMutation object of the builder.
func (gmu *GroupMemberUpdate) Mutation() *GroupMemberMutation {
	return gmu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (gmu *GroupMemberUpdate) ClearUser() *GroupMemberUpdate {
	gmu.mutation.ClearUser()
	return gmu
}

// ClearGroup clears the "group" edge to the Group entity.
func (gmu *GroupMemberUpdate) ClearGroup() *GroupMemberUpdate {
	gmu.mutation.ClearGroup()
	return gmu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (gmu *GroupMemberUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(gmu.hooks) == 0 {
		affected, err = gmu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GroupMemberMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			gmu.mutation = mutation
			affected, err = gmu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(gmu.hooks) - 1; i >= 0; i-- {
			if gmu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = gmu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gmu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (gmu *GroupMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := gmu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (gmu *GroupMemberUpdate) Exec(ctx context.Context) error {
	_, err := gmu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gmu *GroupMemberUpdate) ExecX(ctx context.Context) {
	if err := gmu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (gmu *GroupMemberUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   groupmember.Table,
			Columns: groupmember.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: groupmember.FieldID,
			},
		},
	}
	if ps := gmu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := gmu.mutation.Value(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: groupmember.FieldValue,
		})
	}
	if value, ok := gmu.mutation.GetType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: groupmember.FieldType,
		})
	}
	if gmu.mutation.TypeCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: groupmember.FieldType,
		})
	}
	if value, ok := gmu.mutation.Ref(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: groupmember.FieldRef,
		})
	}
	if gmu.mutation.RefCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: groupmember.FieldRef,
		})
	}
	if gmu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmember.UserTable,
			Columns: []string{groupmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := gmu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmember.UserTable,
			Columns: []string{groupmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if gmu.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmember.GroupTable,
			Columns: []string{groupmember.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: group.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := gmu.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmember.GroupTable,
			Columns: []string{groupmember.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: group.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, gmu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// GroupMemberUpdateOne is the builder for updating a single GroupMember entity.
type GroupMemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupMemberMutation
}

// SetValue sets the "value" field.
func (gmuo *GroupMemberUpdateOne) SetValue(s string) *GroupMemberUpdateOne {
	gmuo.mutation.SetValue(s)
	return gmuo
}

// SetType sets the "type" field.
func (gmuo *GroupMemberUpdateOne) SetType(s string) *GroupMemberUpdateOne {
	gmuo.mutation.SetType(s)
	return gmuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (gmuo *GroupMemberUpdateOne) SetNillableType(s *string) *GroupMemberUpdateOne {
	if s != nil {
		gmuo.SetType(*s)
	}
	return gmuo
}

// ClearType clears the value of the "type" field.
func (gmuo *GroupMemberUpdateOne) ClearType() *GroupMemberUpdateOne {
	gmuo.mutation.ClearType()
	return gmuo
}

// SetRef sets the "ref" field.
func (gmuo *GroupMemberUpdateOne) SetRef(s string) *GroupMemberUpdateOne {
	gmuo.mutation.SetRef(s)
	return gmuo
}

// SetNillableRef sets the "ref" field if the given value is not nil.
func (gmuo *GroupMemberUpdateOne) SetNillableRef(s *string) *GroupMemberUpdateOne {
	if s != nil {
		gmuo.SetRef(*s)
	}
	return gmuo
}

// ClearRef clears the value of the "ref" field.
func (gmuo *GroupMemberUpdateOne) ClearRef() *GroupMemberUpdateOne {
	gmuo.mutation.ClearRef()
	return gmuo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (gmuo *GroupMemberUpdateOne) SetUserID(id uuid.UUID) *GroupMemberUpdateOne {
	gmuo.mutation.SetUserID(id)
	return gmuo
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (gmuo *GroupMemberUpdateOne) SetNillableUserID(id *uuid.UUID) *GroupMemberUpdateOne {
	if id != nil {
		gmuo = gmuo.SetUserID(*id)
	}
	return gmuo
}

// SetUser sets the "user" edge to the User entity.
func (gmuo *GroupMemberUpdateOne) SetUser(u *User) *GroupMemberUpdateOne {
	return gmuo.SetUserID(u.ID)
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (gmuo *GroupMemberUpdateOne) SetGroupID(id uuid.UUID) *GroupMemberUpdateOne {
	gmuo.mutation.SetGroupID(id)
	return gmuo
}

// SetNillableGroupID sets the "group" edge to the Group entity by ID if the given value is not nil.
func (gmuo *GroupMemberUpdateOne) SetNillableGroupID(id *uuid.UUID) *GroupMemberUpdateOne {
	if id != nil {
		gmuo = gmuo.SetGroupID(*id)
	}
	return gmuo
}

// SetGroup sets the "group" edge to the Group entity.
func (gmuo *GroupMemberUpdateOne) SetGroup(g *Group) *GroupMemberUpdateOne {
	return gmuo.SetGroupID(g.ID)
}

// Mutation returns the GroupMemberMutation object of the builder.
func (gmuo *GroupMemberUpdateOne) Mutation() *GroupMemberMutation {
	return gmuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (gmuo *GroupMemberUpdateOne) ClearUser() *GroupMemberUpdateOne {
	gmuo.mutation.ClearUser()
	return gmuo
}

// ClearGroup clears the "group" edge to the Group entity.
func (gmuo *GroupMemberUpdateOne) ClearGroup() *GroupMemberUpdateOne {
	gmuo.mutation.ClearGroup()
	return gmuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (gmuo *GroupMemberUpdateOne) Select(field string, fields ...string) *GroupMemberUpdateOne {
	gmuo.fields = append([]string{field}, fields...)
	return gmuo
}

// Save executes the query and returns the updated GroupMember entity.
func (gmuo *GroupMemberUpdateOne) Save(ctx context.Context) (*GroupMember, error) {
	var (
		err  error
		node *GroupMember
	)
	if len(gmuo.hooks) == 0 {
		node, err = gmuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GroupMemberMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			gmuo.mutation = mutation
			node, err = gmuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(gmuo.hooks) - 1; i >= 0; i-- {
			if gmuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = gmuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gmuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (gmuo *GroupMemberUpdateOne) SaveX(ctx context.Context) *GroupMember {
	node, err := gmuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (gmuo *GroupMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := gmuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gmuo *GroupMemberUpdateOne) ExecX(ctx context.Context) {
	if err := gmuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (gmuo *GroupMemberUpdateOne) sqlSave(ctx context.Context) (_node *GroupMember, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   groupmember.Table,
			Columns: groupmember.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: groupmember.FieldID,
			},
		},
	}
	id, ok := gmuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GroupMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := gmuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, groupmember.FieldID)
		for _, f := range fields {
			if !groupmember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != groupmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := gmuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := gmuo.mutation.Value(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: groupmember.FieldValue,
		})
	}
	if value, ok := gmuo.mutation.GetType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: groupmember.FieldType,
		})
	}
	if gmuo.mutation.TypeCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: groupmember.FieldType,
		})
	}
	if value, ok := gmuo.mutation.Ref(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: groupmember.FieldRef,
		})
	}
	if gmuo.mutation.RefCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: groupmember.FieldRef,
		})
	}
	if gmuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmember.UserTable,
			Columns: []string{groupmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := gmuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmember.UserTable,
			Columns: []string{groupmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if gmuo.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmember.GroupTable,
			Columns: []string{groupmember.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: group.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := gmuo.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmember.GroupTable,
			Columns: []string{groupmember.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: group.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &GroupMember{config: gmuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, gmuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
