// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/cybozu-go/scim-server/ent/ims"
	"github.com/google/uuid"
)

// IMS is the model entity for the IMS schema.
type IMS struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Display holds the value of the "display" field.
	Display string `json:"display,omitempty"`
	// Primary holds the value of the "primary" field.
	Primary bool `json:"primary,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Value holds the value of the "value" field.
	Value      string `json:"value,omitempty"`
	user_imses *uuid.UUID
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IMS) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case ims.FieldPrimary:
			values[i] = new(sql.NullBool)
		case ims.FieldID:
			values[i] = new(sql.NullInt64)
		case ims.FieldDisplay, ims.FieldType, ims.FieldValue:
			values[i] = new(sql.NullString)
		case ims.ForeignKeys[0]: // user_imses
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			return nil, fmt.Errorf("unexpected column %q for type IMS", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IMS fields.
func (i *IMS) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for j := range columns {
		switch columns[j] {
		case ims.FieldID:
			value, ok := values[j].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			i.ID = int(value.Int64)
		case ims.FieldDisplay:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display", values[j])
			} else if value.Valid {
				i.Display = value.String
			}
		case ims.FieldPrimary:
			if value, ok := values[j].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field primary", values[j])
			} else if value.Valid {
				i.Primary = value.Bool
			}
		case ims.FieldType:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[j])
			} else if value.Valid {
				i.Type = value.String
			}
		case ims.FieldValue:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[j])
			} else if value.Valid {
				i.Value = value.String
			}
		case ims.ForeignKeys[0]:
			if value, ok := values[j].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_imses", values[j])
			} else if value.Valid {
				i.user_imses = new(uuid.UUID)
				*i.user_imses = *value.S.(*uuid.UUID)
			}
		}
	}
	return nil
}

// Update returns a builder for updating this IMS.
// Note that you need to call IMS.Unwrap() before calling this method if this IMS
// was returned from a transaction, and the transaction was committed or rolled back.
func (i *IMS) Update() *IMSUpdateOne {
	return (&IMSClient{config: i.config}).UpdateOne(i)
}

// Unwrap unwraps the IMS entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (i *IMS) Unwrap() *IMS {
	tx, ok := i.config.driver.(*txDriver)
	if !ok {
		panic("ent: IMS is not a transactional entity")
	}
	i.config.driver = tx.drv
	return i
}

// String implements the fmt.Stringer.
func (i *IMS) String() string {
	var builder strings.Builder
	builder.WriteString("IMS(")
	builder.WriteString(fmt.Sprintf("id=%v", i.ID))
	builder.WriteString(", display=")
	builder.WriteString(i.Display)
	builder.WriteString(", primary=")
	builder.WriteString(fmt.Sprintf("%v", i.Primary))
	builder.WriteString(", type=")
	builder.WriteString(i.Type)
	builder.WriteString(", value=")
	builder.WriteString(i.Value)
	builder.WriteByte(')')
	return builder.String()
}

// IMSs is a parsable slice of IMS.
type IMSs []*IMS

func (i IMSs) config(cfg config) {
	for _i := range i {
		i[_i].config = cfg
	}
}
