// Code generated by entc, DO NOT EDIT.

package photo

const (
	// Label holds the string label denoting the photo type in the database.
	Label = "photo"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDisplay holds the string denoting the display field in the database.
	FieldDisplay = "display"
	// FieldPrimary holds the string denoting the primary field in the database.
	FieldPrimary = "primary"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// Table holds the table name of the photo in the database.
	Table = "photos"
)

// Columns holds all SQL columns for photo fields.
var Columns = []string{
	FieldID,
	FieldDisplay,
	FieldPrimary,
	FieldType,
	FieldValue,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "photos"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_photos",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
