// Code generated by ent, DO NOT EDIT.

package photo

import (
	"entgo.io/ent"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the photo type in the database.
	Label = "photo"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDisplay holds the string denoting the display field in the database.
	FieldDisplay = "display"
	// FieldPrimary holds the string denoting the primary field in the database.
	FieldPrimary = "primary"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the photo in the database.
	Table = "photos"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "photos"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_photos"
)

// Columns holds all SQL columns for photo fields.
var Columns = []string{
	FieldID,
	FieldDisplay,
	FieldPrimary,
	FieldType,
	FieldValue,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "photos"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_photos",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/cybozu-go/scim-server/ent/runtime"
//
var (
	Hooks [1]ent.Hook
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
