// Code generated by entc, DO NOT EDIT.

package groupmember

const (
	// Label holds the string label denoting the groupmember type in the database.
	Label = "group_member"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldRef holds the string denoting the ref field in the database.
	FieldRef = "ref"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// Table holds the table name of the groupmember in the database.
	Table = "group_members"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "group_members"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_groups"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "group_members"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_members"
)

// Columns holds all SQL columns for groupmember fields.
var Columns = []string{
	FieldID,
	FieldValue,
	FieldType,
	FieldRef,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "group_members"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"group_members",
	"user_groups",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
