// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Email is the predicate function for email builders.
type Email func(*sql.Selector)

// Entitlement is the predicate function for entitlement builders.
type Entitlement func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Names is the predicate function for names builders.
type Names func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
